#!/system/bin/sh
# Host Script xD

hostn="/system/etc/hosts"
hosto="/system/etc/host"

rm -f $hostn
mv $hosto $hostn;
chmod 644 $hostn;

if [ ! -f $hosto ]; then
    rm -f /system/etc/init.d/04host;
fi;
